<?php

$query3 = "SELECT DISTINCT
  CASE
    WHEN OBI_RECID = '5' THEN 'SIAP STRUK'
  END AS STATUS,
  SUBSTR(OBI_NOPB, 1, 7) AS NO_PB,
  TO_CHAR(OBI_CREATEDT, 'DD/MM/YY HH24:MI:SS') AS TGL_PB,
  TO_CHAR(OBI_TGLORDER, 'DD/MM/YY HH24:MI:SS') AS TGL_ORDER,
  OBI_KDMEMBER AS KODE_MEMBER,
  CUS_NAMAMEMBER AS NAMA_MEMBER,
  OBI_REALORDER + OBI_REALPPN - OBI_REALDISKON AS REALORDER,
  TO_CHAR(DSP_CREATE_DT, 'DD/MM/YY HH24:MI:SS') AS TGL_DSP,
  OBI_TIPEBAYAR AS TIPE_BAYAR,
  AWI_PINCODE AS PIN,
  STATUS_PIN,
  TO_CHAR(STI_CREATE_DT, 'DD/MM/YY HH24:MI:SS') AS TGL_INPUT_PIN,
  AWI_NOAWB,
  STI_NOSERAHTERIMA,
  STI_DRIVERNAME
FROM (
  SELECT
    OBI_RECID,
    OBI_NOPB,
    OBI_CREATEDT,
    OBI_KDMEMBER,
    CUS_NAMAMEMBER,
    OBI_REALORDER,
    OBI_REALPPN,
    OBI_REALDISKON,
    DSP_CREATE_DT,
    OBI_TGLORDER,
    OBI_TIPEBAYAR,
    AWI_PINCODE,
    CASE
      WHEN STI_NOSERAHTERIMA IS NOT NULL THEN 'SUDAH INPUT PIN A'
      WHEN RESPONSE LIKE '%Gagal, Kode AWB belum terbentuk%' THEN 'Gagal, Kode AWB Belum Terbentuk'
      WHEN RESPONSE LIKE '%Connection Failed%' THEN 'Connection Failed'
      WHEN RESPONSE LIKE '%Server bermasalah%' THEN 'Server Bermasalah'
      WHEN RESPONSE LIKE '%Input CODValue (DeliveryInfo)%' THEN 'Input CODValue (INFO IPP)'
      WHEN RESPONSE LIKE '%Data penerima harus diisi%' THEN 'Data Penerima Harus Diisi (INFO IPP)'
      ELSE 'BELUM INPUT PIN A'
    END AS STATUS_PIN,
    STI_CREATE_DT,
    AWI_NOAWB,
    STI_NOSERAHTERIMA,
    STI_DRIVERNAME,
    ROW_NUMBER() OVER (PARTITION BY RESPONSE ORDER BY CREATE_DT DESC) AS rnk
  FROM
    TBTR_OBI_H
    LEFT JOIN TBMASTER_CUSTOMER ON OBI_KDMEMBER = CUS_KODEMEMBER
    LEFT JOIN TBTR_AWB_IPP ON OBI_NOPB = AWI_NOPB
    LEFT JOIN TBTR_SERAHTERIMA_IPP ON STI_NOORDER = AWI_NOORDER
    LEFT JOIN LOG_CREATEAWB ON OBI_NOPB = NOPB
    LEFT JOIN TBTR_DSP_SPI ON OBI_NOPB = DSP_NOPB
  WHERE
    obi_kdekspedisi <> 'Ambil di Stock Point Indogrosir'
    and OBI_RECID = '5'
    AND OBI_TGLORDER <= (CURRENT_DATE - INTERVAL '1 day') + INTERVAL '16 hours 45 minutes'
    AND OBI_TGLORDER < CURRENT_DATE
) AS Z
WHERE rnk = 1
ORDER BY STATUS_PIN, AWI_NOAWB";

// Create connection to PG
require_once '../helper/connection.php';
$stmt = $conn->query($query3); // Eksekusi query dengan PDO
