<?php 

$query = "select PRD_KODEDIVISI divisi, LKS_KODERAK||'.'||LKS_KODESUBRAK||'.'||LKS_TIPERAK||'.'||LKS_SHELVINGRAK||'.'||LKS_NOURUT 			AS LOKASI, LKS_PRDCD, prd_deskripsipanjang,PRD_UNIT, PRD_FRAC, LKS_QTY, LKS_EXPDATE,PRD_FRAC * MPT_MAXQTY AS MAX_PALET
			from TBMASTER_lokasi
			LEFT JOIN TBMASTER_PRODMAST ON PRD_PRDCD = LKS_PRDCD
			LEFT JOIN TBMASTER_MAXPALET ON MPT_PRDCD = LKS_PRDCD
			WHERE LKS_QTY < (PRD_FRAC * MPT_MAXQTY) 
			AND LKS_TIPERAK = 'S'
			AND PRD_KODEDIVISI <> '5'";

	if ($divisi != 'ALL') {
	 $query .= "	AND PRD_KODEDIVISI = '{$divisi}' "; }

	$query .= "	ORDER BY LKS_PRDCD ";




?>
